# Homework 3  - Tryout pandas and numpy

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [3]:
%matplotlib inline       
import numpy as np
import pandas as pd      # Import 'numpy' and 'pandas' modules

ccp = pd.read_csv("data/ccp_current_csv.csv")  # Load the data
ccp.head()                                     # Prints the first 5 observations

             STREET QUADRANT  FROMINTERSECTION              TOINTERSECTION  \
0           13th St       NW        Kennedy St               Longfellow St   
1              S St       NW  North Capitol St                      3rd St   
2  Rhode Island Ave       NE  Brentwood Rd (W)            Brentwood Rd (M)   
3           Mill Rd       NW           27th St                  Cul De Sac   
4  Rhode Island Ave       NE  Brentwood Rd (M)  14th St  Evarts St  Montan   

   NOOFBLOCKS      ...              PROJECTMGR  PROJECTID        TEAMREP  \
0           1      ...         Paul Stephenson       5834        O. Hill   
1           3      ...                     NaN       2467            NaN   
2           1      ...       Mohamed Abdullahi       5486   Said Cherifi   
3           1      ...         Maduabuchi Udeh       5796  Michael Jelen   
4           2      ...                     NaN       8237            NaN   

                  EMAIL  CONTACTPHONE  
0                   NaN  202-671-4

### 3.1.a  what is its shape and what does that mean?

In [4]:
ccp.shape    # The dataset has 465 observations with 27 variables

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [5]:
qd = ccp['QUADRANT'].count()     # Gives the total number of rows in 'QUADRANT'
print(qd)   

ccp['QUADRANT'].value_counts()   # Gives the number of rows in each 'QUADRANT'

465


NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [6]:
import numpy as np

a = np.array([1.,2.,3.,4.])
b = np.array([5.,6.,7.,8.])

print(a.dtype)              # Checks the datatype of an array variable
print(a+b)

np.add(a,b)

float64
[  6.   8.  10.  12.]


array([  6.,   8.,  10.,  12.])

### 3.3.2 subtraction a-b

In [7]:
print(a-b)

np.subtract(a,b)

[-4. -4. -4. -4.]


array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [8]:
print(a*b)

np.multiply(a,b)

[  5.  12.  21.  32.]


array([  5.,  12.,  21.,  32.])

### 3.3.4 divsion a/b

In [9]:
print(a/b)

np.divide(a,b)

[ 0.2         0.33333333  0.42857143  0.5       ]


array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

### 3.3.5 modulo  a%b

In [10]:
print(a%b)

np.mod(a,b)

[ 1.  2.  3.  4.]


array([ 1.,  2.,  3.,  4.])

### 3.3.6 power  a^b

In [11]:
print(pow(a,b))

np.power(a,b)

[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [27]:
# Estimates the burden of diseases, injuries, and risk factors globally and for 21 regions for 1990 and 2010 
# via IHME (Institute for Health Metrics and Evaluations).

%matplotlib inline       
import numpy as np
import pandas as pd      # Import 'numpy' and 'pandas' modules

# Set pandas options controlling output format
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 15)
pd.set_option('display.width', 120)

gbd = pd.read_csv("data/IHME_GBD_2010.csv")  # Load the data
gbd.head()                                   # Prints the first 5 observations

  Country Code Country Name  Year  Age Group     Sex Number of Deaths Death Rate Per 100,000
0          AFG  Afghanistan  1970   0-6 days    Male           19,241             318,292.90
1          AFG  Afghanistan  1970   0-6 days  Female           12,600             219,544.20
2          AFG  Afghanistan  1970   0-6 days    Both           31,840             270,200.70
3          AFG  Afghanistan  1970  7-27 days    Male           15,939              92,701.00
4          AFG  Afghanistan  1970  7-27 days  Female           11,287              68,594.50

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [28]:
gbd.dtypes    # Check the data types of the colums in the dataset

Country Code              object
Country Name              object
Year                       int64
Age Group                 object
Sex                       object
Number of Deaths          object
Death Rate Per 100,000    object
dtype: object

I spent about 2 hours trying to convert the dtype of a column from object to int64 or float64 to get the right results. Atlast, I was able to. I don't know where I went wrong with this. 

In [29]:
print(gbd['Country Name'].count())         
gbd['Country Name'].value_counts() 

58905


Latvia                 315
Cuba                   315
Brazil                 315
Antigua and Barbuda    315
Slovakia               315
Gabon                  315
Nigeria                315
                      ... 
Norway                 315
Guatemala              315
Uruguay                315
Solomon Islands        315
Cambodia               315
Burundi                315
Nicaragua              315
Name: Country Name, Length: 187, dtype: int64

In [30]:
gbd.duplicated().sum()              # To check for any duplicated values

0

In [31]:
grouped_by_age = gbd.groupby('Age Group')    
print(grouped_by_age.ngroups)                # Gives number of groups when grouped by 'Age'

21


In [32]:
grouped_by_sex = gbd.groupby('Sex')
print(grouped_by_sex.ngroups)        # Number of groups in the column 'Sex'
print(grouped_by_sex.count())        # get the count of items in each column of each group
print(grouped_by_sex.size())         # get how many items are in each group (Both, Female and Male)

3
        Country Code  Country Name   Year  Age Group  Number of Deaths  Death Rate Per 100,000
Sex                                                                                           
Both           19635         19635  19635      19635             19635                   19635
Female         19635         19635  19635      19635             19635                   19635
Male           19635         19635  19635      19635             19635                   19635
Sex
Both      19635
Female    19635
Male      19635
dtype: int64


In [33]:
gbd_update1 = gbd.loc[gbd["Sex"] != 'Both']
gbd_update1       # Removed rows containing 'Sex' as 'Both' as it contained sum of 'Number of deaths' of both males and females 

      Country Code Country Name  Year    Age Group     Sex Number of Deaths Death Rate Per 100,000
0              AFG  Afghanistan  1970     0-6 days    Male           19,241             318,292.90
1              AFG  Afghanistan  1970     0-6 days  Female           12,600             219,544.20
3              AFG  Afghanistan  1970    7-27 days    Male           15,939              92,701.00
4              AFG  Afghanistan  1970    7-27 days  Female           11,287              68,594.50
6              AFG  Afghanistan  1970  28-364 days    Male           37,513              15,040.10
7              AFG  Afghanistan  1970  28-364 days  Female           32,113              13,411.80
9              AFG  Afghanistan  1970    1-4 years    Male           36,694               4,288.20
...            ...          ...   ...          ...     ...              ...                    ...
58894          ZWE     Zimbabwe  2010  70-74 years  Female            4,677               5,755.00
58896     

In [34]:
grouped_by_country = gbd_update1.groupby('Country Name')
print(grouped_by_country.ngroups)                  # Number of countries   

print(gbd_update1['Country Name'].nunique())        # Number of non-null unique countries 

187
187


In [35]:
group_by_year = gbd_update1.groupby(['Year'])   # Group by Year
group_by_year.head(5)                          # Prints first 5 rows in each year

    Country Code Country Name  Year    Age Group     Sex Number of Deaths Death Rate Per 100,000
0            AFG  Afghanistan  1970     0-6 days    Male           19,241             318,292.90
1            AFG  Afghanistan  1970     0-6 days  Female           12,600             219,544.20
3            AFG  Afghanistan  1970    7-27 days    Male           15,939              92,701.00
4            AFG  Afghanistan  1970    7-27 days  Female           11,287              68,594.50
6            AFG  Afghanistan  1970  28-364 days    Male           37,513              15,040.10
63           AFG  Afghanistan  1980     0-6 days    Male           16,152             235,901.00
64           AFG  Afghanistan  1980     0-6 days  Female           10,838             167,053.30
..           ...          ...   ...          ...     ...              ...                    ...
193          AFG  Afghanistan  2000    7-27 days  Female            9,189              28,855.10
195          AFG  Afghanistan 

In [36]:
group_by_year['Number of Deaths'].dtype

Year
1970    object
1980    object
1990    object
2000    object
2010    object
Name: Number of Deaths, dtype: object

In [37]:
grouped_by_age = gbd_update1.groupby('Age Group')            # Number of of  Deaths by Age Group

In [38]:
grouped_by_age.size()     # get how many items are in each group

Age Group
0-6 days       1870
1-4 years      1870
10-14 years    1870
15-19 years    1870
20-24 years    1870
25-29 years    1870
28-364 days    1870
               ... 
60-64 years    1870
65-69 years    1870
7-27 days      1870
70-74 years    1870
75-79 years    1870
80+ years      1870
All ages       1870
Length: 21, dtype: int64

In [39]:
grouped_by_age.get_group('7-27 days')[:10]         # get the first 10 rows of data in one specific group '7-27 days'

    Country Code Country Name  Year  Age Group     Sex Number of Deaths Death Rate Per 100,000
3            AFG  Afghanistan  1970  7-27 days    Male           15,939              92,701.00
4            AFG  Afghanistan  1970  7-27 days  Female           11,287              68,594.50
66           AFG  Afghanistan  1980  7-27 days    Male           12,551              63,362.90
67           AFG  Afghanistan  1980  7-27 days  Female            9,217              48,823.20
129          AFG  Afghanistan  1990  7-27 days    Male            8,325              39,454.30
130          AFG  Afghanistan  1990  7-27 days  Female            6,203              30,916.80
192          AFG  Afghanistan  2000  7-27 days    Male           12,365              36,914.40
193          AFG  Afghanistan  2000  7-27 days  Female            9,189              28,855.10
255          AFG  Afghanistan  2010  7-27 days    Male            7,639              19,244.20
256          AFG  Afghanistan  2010  7-27 days  Fe

In [40]:
grouped_by_age.nth(0)            # get the 1st item in each group

            Country Code Country Name Death Rate Per 100,000 Number of Deaths   Sex  Year
Age Group                                                                                
0-6 days             AFG  Afghanistan             318,292.90           19,241  Male  1970
1-4 years            AFG  Afghanistan               4,288.20           36,694  Male  1970
10-14 years          AFG  Afghanistan                  230.8            1,723  Male  1970
15-19 years          AFG  Afghanistan                  282.9            1,816  Male  1970
20-24 years          AFG  Afghanistan                  392.9            2,240  Male  1970
25-29 years          AFG  Afghanistan                  432.4            2,050  Male  1970
28-364 days          AFG  Afghanistan              15,040.10           37,513  Male  1970
...                  ...          ...                    ...              ...   ...   ...
60-64 years          AFG  Afghanistan               4,229.20            4,239  Male  1970
65-69 year

In [41]:
grouped_by_age.nth(2)            # get the 3rd item in each group

            Country Code Country Name Death Rate Per 100,000 Number of Deaths   Sex  Year
Age Group                                                                                
0-6 days             AFG  Afghanistan             235,901.00           16,152  Male  1980
1-4 years            AFG  Afghanistan               2,713.30           30,885  Male  1980
10-14 years          AFG  Afghanistan                    321            2,912  Male  1980
15-19 years          AFG  Afghanistan                  443.5            3,396  Male  1980
20-24 years          AFG  Afghanistan                  599.1            3,859  Male  1980
25-29 years          AFG  Afghanistan                  648.6            3,509  Male  1980
28-364 days          AFG  Afghanistan              10,792.30           32,316  Male  1980
...                  ...          ...                    ...              ...   ...   ...
60-64 years          AFG  Afghanistan               4,813.20            5,496  Male  1980
65-69 year

In [42]:
grouped_by_age['Number of Deaths'].sum()

Age Group
0-6 days       19,24112,60016,15210,83812,6358,63619,34513,22...
1-4 years      36,69432,84830,88527,50618,02915,94327,29024,0...
10-14 years    1,7231,8062,9122,4731,2321,4992,2432,9822,2962...
15-19 years    1,8161,9023,3962,7961,7731,9163,3463,8164,0794...
20-24 years    2,2402,6303,8593,4402,1202,3233,9504,5194,8584...
25-29 years    2,0502,8893,5093,7101,9102,4913,5564,8774,2574...
28-364 days    37,51332,11332,31627,19122,71119,28634,46929,4...
                                     ...                        
60-64 years    4,2394,5145,4965,4424,1094,3147,4758,0449,1049...
65-69 years    3,9684,5804,9445,4493,8604,4537,0438,2968,5919...
7-27 days      15,93911,28712,5519,2178,3256,20312,3659,1897,...
70-74 years    3,4354,4044,1115,1873,3874,4286,1708,2557,7269...
75-79 years    2,3743,1292,7763,7412,4303,3414,4216,2455,7407...
80+ years      1,6762,1802,0942,8311,9192,6803,5605,1384,8656...
All ages       153,656138,181154,935137,110103,30597,331169,5...
Name: Number of

## Reference and Dataset
In the DataSets section, I used the data from 'Health' i.e, Global Burden of disease. The dataset is in the link provided below:
https://public.tableau.com/en-us/s/resources